theme: jekyll-theme-slate
name: Lamplusの日記name
title: Lamplusの日記
name.title: Lamplusの日記name.title
site.title: Lamplusの日記site.title

description: 日々の勉強内容、調べたことなどを記載していきます。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" 

